name: RN Android No ProGuard Test

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [arm64-v8a, x86, x86_64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build APK (${{ matrix.arch }})
        run: |
          cd android
          ./gradlew assembleRelease -PtargetArch=${{ matrix.arch }}

  universal:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 生成 Universal APK
      - name: Build Universal APK
        run: |
          cd android
          ./gradlew assembleRelease

      # 列出 APK 目录，方便确认文件名
      - name: Check APK outputs
        run: |
          ls -R android/app/build/outputs/apk

      # 自动匹配并拷贝 APK
      - name: Collect Universal APK
        run: |
          mkdir -p output
          cp android/app/build/outputs/apk/release/*.apk output/

      - name: Upload Universal APK
        uses: actions/upload-artifact@v3
        with:
          name: universal-apk
          path: output/*.apk
